# GitHub Pages Configuration for De Beauty Schuur
# Static HTML site - minimal Jekyll configuration

# Basic site information
title: De Beauty Schuur
description: Professionele beauty salon in Nederland - behandelingen, PMU, huidverzorging en meer
url: "https://fsdaniel.github.io"
baseurl: "/paschuur"

# Disable Jekyll processing for static HTML
plugins: []

# Exclude files that shouldn't be processed
exclude:
  - README.md
  - PLANNING.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .git
  - .gitignore

# Include all HTML, CSS, JS files
include:
  - "*.html"
  - "*.css"
  - "*.js"
  - "assets/"
  - "behandelingen/"

# Disable Jekyll features we don't need
markdown: kramdown
highlighter: rouge
theme: null

# SEO metadata
author: De Beauty Schuur
social:
  name: De Beauty Schuur
  links:
    - https://www.instagram.com/debeautyschuur
    - https://www.facebook.com/debeautyschuur
